stages:
  - test
  - build

lint-rst:
  services:
    - image:ada-trainings
  stage: build
  script:
      - python3 contrib/fix_broken_titles.py --check
      - python3 contrib/ci/fix_prelude.py
  rules:
    - if: $CI_COMMIT_BRANCH == ""
    - if: $CI_COMMIT_BRANCH != ""

check_main_is_properly_setup:
  services:
    - image:e3
  stage: test
  script:
    - test ! -e DO_NOT_MERGE.*
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"

check_syntax:
  stage: test
  services:
    - image:lint

  script:
    - autolint --check --output-code-climate-report=code_quality_report.json .

  allow_failure: false

  artifacts:
    when: always
    reports:
      codequality: code_quality_report.json

  rules:
    - if: $CI_COMMIT_BRANCH == ""
    - if: $CI_COMMIT_BRANCH != ""
