stages:
  - test
  - build

lint-rst:
  services:
    - image:ada-trainings
  stage: build
  script:
      - python3 contrib/fix_broken_titles.py --check
      - python3 contrib/ci/fix_prelude.py

check_syntax:
  stage: test
  services:
    - image:lint

  script:
    - autolint --check --output-code-climate-report=code_quality_report.json .

  allow_failure: false

  artifacts:
    when: always
    reports:
      codequality: code_quality_report.json
