check-lint:
  services:
    - image:ada-trainings
  stage: build
  script:
      - python3 contrib/fix_broken_titles.py --check
      - python3 contrib/ci/fix_prelude.py

check-black:
  services:
    - image:ada-trainings
  stage: build
  script:
    - python3 -m black --check $(find contrib -name '*.py')
    - python3 -m black --check $(find pandoc -name '*.py')
